// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIYBJapLcdfmahVL9uTP6RpM4efO_LCCI',
    appId: '1:842027119105:web:e2f1bc438faf5f0ac14600',
    messagingSenderId: '842027119105',
    projectId: 'aironiversity-50ae8',
    authDomain: 'aironiversity-50ae8.firebaseapp.com',
    databaseURL:
        'https://aironiversity-50ae8-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'aironiversity-50ae8.firebasestorage.app',
    measurementId: 'G-FHCNX04HBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0tj74PMZzUkAfAHbC-gr89kbswY-pBEA',
    appId: '1:842027119105:android:0ee043112467d93ec14600',
    messagingSenderId: '842027119105',
    projectId: 'aironiversity-50ae8',
    databaseURL:
        'https://aironiversity-50ae8-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'aironiversity-50ae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6BKvJPOAJ4GihrX2VeFwzf3Rwjhdgytk',
    appId: '1:842027119105:ios:541fcddbfa00fd40c14600',
    messagingSenderId: '842027119105',
    projectId: 'aironiversity-50ae8',
    databaseURL:
        'https://aironiversity-50ae8-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'aironiversity-50ae8.firebasestorage.app',
    iosBundleId: 'com.example.crudapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6BKvJPOAJ4GihrX2VeFwzf3Rwjhdgytk',
    appId: '1:842027119105:ios:541fcddbfa00fd40c14600',
    messagingSenderId: '842027119105',
    projectId: 'aironiversity-50ae8',
    databaseURL:
        'https://aironiversity-50ae8-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'aironiversity-50ae8.firebasestorage.app',
    iosBundleId: 'com.example.crudapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIYBJapLcdfmahVL9uTP6RpM4efO_LCCI',
    appId: '1:842027119105:web:0e7d31df1607b330c14600',
    messagingSenderId: '842027119105',
    projectId: 'aironiversity-50ae8',
    authDomain: 'aironiversity-50ae8.firebaseapp.com',
    databaseURL:
        'https://aironiversity-50ae8-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'aironiversity-50ae8.firebasestorage.app',
    measurementId: 'G-EF7SCZ8EH4',
  );
}
